name: Unit-tests on Windows GPU
on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
    with:
      repository: pytorch/audio
      runner: windows.g5.4xlarge.nvidia.gpu
      script: "# Mark Build Directory Safe\ngit config --global --add safe.directory\
        \ /__w/audio/audio\n\n# Set up Environment Variables\nexport PYTHON_VERSION=\"\
        3.10\"\nexport CUDA_VERSION=12.6\nexport PIP_PROGRESS_BAR=off\nexport CONDA_QUIET=1\n\
        export USE_CUDA=1\nexport CUBLAS_WORKSPACE_CONFIG=:4096:8\n\n#  Set CHANNEL\n\
        if [[(${GITHUB_EVENT_NAME} = 'pull_request' && (${GITHUB_BASE_REF} = 'release'*))\
        \ || (${GITHUB_REF} = 'refs/heads/release'*) ]]; then\n  export UPLOAD_CHANNEL=test\n\
        else\n  export UPLOAD_CHANNEL=nightly\nfi\n\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CMD_APPLY_CMVN_SLIDING=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CMD_COMPUTE_FBANK_FEATS=true\nexport\
        \ TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CMD_COMPUTE_KALDI_PITCH_FEATS=true\nexport\
        \ TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CMD_COMPUTE_MFCC_FEATS=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CMD_COMPUTE_SPECTROGRAM_FEATS=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CMD_SOX=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_KALDI=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_SOX=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_ON_PYTHON_310=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_MOD_sentencepiece=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_AUDIO_OUT_DEVICE=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_MACOS=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_CUDA_SMALL_MEMORY=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_TEMPORARY_DISABLED=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_QUANTIZATION=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_CTC_DECODER=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_MOD_unidecode=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_MOD_inflect=true\nexport TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_MOD_pytorch_lightning=true\n\
        export TORCHAUDIO_TEST_ALLOW_SKIP_IF_NO_MOD_sentencepiece=true\n\n.github/scripts/unittest-windows/setup_env.sh\n\
        .github/scripts/unittest-windows/install.sh\n.github/scripts/unittest-windows/run_test.sh\n"
      timeout: 360
